### ISSUE TITLE
compatibility from 1.14 to 1.19 but not 1.18.2?

### ISSUE THREAD

**Issue by Herobrine2143** [uku3lig/betterhurtcam#7]
so I added this mod for a Minecraft version 1.18.2 but I'm getting this error that there's no compatibility for 1.18.2

![image](https://user-images.githubusercontent.com/22053132/224484549-d2d995cc-3ef2-4c75-894b-b32007f159a6.png)

Version of the mod is 1.5.2 (is also in the picture)

**Comment by uku3lig** [comment]
All of these show when there is *another* mod resolution problem, so you might want to check what you have to do to fix that.

Second thing, all these errors show that the wrong Minecraft version is present, and doesn't show it for 1.18.2 because the `betterhurtcam-mc118` sub-mod *did* find the needed Minecraft version.
